- name: checkout ruby-build repo
  git: >
    repo=git://github.com/sstephenson/ruby-build.git
    dest={{ruby_build_root}}
    accept_hostkey=yes

- name: symlink ruby-build to PATH
  file: >
    src={{ ruby_build_root }}/bin/ruby-build
    dest=/usr/local/bin/ruby-build
    state=link

- name: create gemrc
  template: src=gemrc dest=/etc/gemrc

- name: install default ruby version
  shell: >
    vxvm install ruby {{ ruby_default_version }}
  register: ruby_default_result

- name: capture default ruby location
  shell: >
    vxvm location ruby {{ ruby_default_version }}
  register: ruby_default_location_result

- name: create ruby wrapper for casher
  template: src=casher-ruby dest=/usr/local/bin/casher-ruby mode=0755

- name: symlink default ruby to PATH
  file: >
    src={{ ruby_default_location_result.stdout }}/bin/{{ item }}
    dest=/usr/local/bin/{{ item }}
    state=link
  with_items:
    - "ruby"
    - "rake"
    - "gem"
    - "irb"
    - "bundle"
