- name: download deb package
  get_url: >
    url=http://sphinxsearch.com/files/sphinxsearch_{{ sphinxsearch_version }}-release-0ubuntu12~trusty_amd64.deb
    dest=/tmp/sphinxsearch_{{ sphinxsearch_version }}-release-0ubuntu12~trusty_amd64.deb
    validate_certs=no
  register: sphinxsearch_download_result

- name: install rquired packages
  apt: pkg={{ item }}
  with_items:
    - "libmysqlclient18"
    - "libpq5"
    - "libodbc1"

- name: install package
  shell: >
    dpkg -i /tmp/sphinxsearch_{{ sphinxsearch_version }}-release-0ubuntu12~trusty_amd64.deb
  when: sphinxsearch_download_result | changed
